### ISSUE TITLE
Mainnet vs Mainet

### ISSUE THREAD

**Issue by tomrpl** [deficollective/permission-scanner#2]
There is a naming confusion in the readme or into the script between "mainnet" and "mainet":

https://github.com/deficollective/permission-scanner?tab=readme-ov-file#supported-chains
-> 
"mainnet:": (".etherscan.io", "etherscan.io")

While in the rpc_url is looking after "mainet"
https://github.com/deficollective/permission-scanner/blob/main/src/get_rpc_url.py#L5

And 
the readme has
https://github.com/deficollective/permission-scanner/blob/main/.env.example#L5C46-L6C1
MAINNETRPC instead of 
MAINNET_RPC

I would advise to uniformizing with the naming. 

I can open a PR if you want!

**Comment by flbouchut** [comment]
same issue encountered here, it would be great to fix these 2 naming discrepancies for better onboarding with the tool
